//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAMekaWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string Names { get; set; }
        public string LastNames { get; set; }
        public string DocumentIdentity { get; set; }
        public string Password { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public string Username { get; set; }
        public string Status { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Phone { get; set; }
    }
}
