//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAMekaWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Qualification = new HashSet<Qualification>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int CustomerId { get; set; }
        public string Names { get; set; }
        public string LastNames { get; set; }
        public string DocumentIdentity { get; set; }
        public string Password { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public string Username { get; set; }
        public string Status { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual District District { get; set; }
        public virtual ProvinceId ProvinceId1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qualification> Qualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
