//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAMekaWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> LocalId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.TimeSpan> Schedule { get; set; }
        public string Detail { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Local Local { get; set; }
        public virtual Service Service { get; set; }
    }
}
