//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAMekaWash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceId { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public Nullable<int> LocalId { get; set; }
        public string UrlPhoto { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Status { get; set; }
    }
}
